# Generated by Django 6.0.3 on 2026-03-09 12:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('strategy', 'Strategy'), ('party', 'Party')], max_length=20)),
                ('min_players', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('max_players', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('playtime_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rented', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(editable=False)),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('board_game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='tabletop_club_app.boardgame')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_rented'],
            },
        ),
    ]
