# Generated by Django 6.0.3 on 2026-03-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabletop_club_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='date_returned',
        ),
    ]
