[pytest]
DJANGO_SETTINGS_MODULE = tabletop_club.settings
python_files = tests.py test_*.py *_tests.py

# Filters a warning that says that a staticfiles directory didn't exist. 
# The line of code that causes this warning is necessary for the CSS to load on the deployed site.
# Because it isn't a helpful warning, it has been hidden.
filterwarnings =
    ignore:No directory at:UserWarning